src/main/java/br/com/naldson/parciaiscartola/model/Jogadores.java
package br.com.naldson.parciaiscartola.model;

public class Jogadores implements Comparable<Jogadores> {

    private final Integer id;
    private final String nome;
    private final String foto;
    private double pontos;
    private final int posicaoId;

    public Jogadores(Integer id, String nome, String foto, int posicaoId) {
        this.id = id;
        this.nome = nome;
        this.foto = foto;
        this.posicaoId = posicaoId;
    }

    public int compareTo(Jogadores outro) {
        if (outro.getPosicaoId() > this.posicaoId) {
            return -1;
        } else if (outro.getPosicaoId() < this.posicaoId) {
            return 1;
        }
        return 0;
    }

    public Integer getId() {
        return id;
    }

    public String getNome() {
        return nome;
    }

    public String getFoto() {
        return foto.replace("FORMATO", "140x140");
    }

    public double getPontos() {
        return pontos;
    }

    public void setPontos(double pontos) {
        this.pontos = pontos;
    }

    public int getPosicaoId() {
        return posicaoId;
    }
}

src/main/java/br/com/naldson/parciaiscartola/model/Liga.java
package br.com.naldson.parciaiscartola.model;

import java.util.HashMap;

public final class Liga {

    private HashMap<String, String> times;

    public Liga() {
        this.times = new HashMap();
        adicionaTimes();
    }

    public void adicionaTimes() {
        times.put("ssc-napoleza", "https://api.cartolafc.globo.com/time/ssc-napoleza");
        times.put("turmada-resenha-fc", "https://api.cartolafc.globo.com/time/Turmada-resenha-fc");
        times.put("ikarosgrill-fc", "https://api.cartolafc.globo.com/time/IkarosGrill-FC");
        times.put("fec18-ec", "https://api.cartolafc.globo.com/time/FEC18-EC");
        times.put("rio-negro-fcm", "https://api.cartolafc.globo.com/time/Rio-Negro-Fcm");
        times.put("spartacus-1000", "https://api.cartolafc.globo.com/time/Spartacus-1000");
        times.put("real-mdg-fc", "https://api.cartolafc.globo.com/time/Real-mdg-fc");
        times.put("six-nations-fc", "https://api.cartolafc.globo.com/time/six-nations-fc");
        times.put("elieel-fc", "https://api.cartolafc.globo.com/time/elieel-fc");
        times.put("25-de-dezembro-f-c", "https://api.cartolafc.globo.com/time/25-de-dezembro-f-c");
        times.put("denismengao", "https://api.cartolafc.globo.com/time/denismengao");
        times.put("atletic-de-esparta", "https://api.cartolafc.globo.com/time/atletic-de-esparta");
        times.put("crtorquato", "https://api.cartolafc.globo.com/time/crtorquato");
        times.put("igor-ceara-fc", "https://api.cartolafc.globo.com/time/igor-ceara-fc");
        times.put("joec", "https://api.cartolafc.globo.com/time/joec");
        times.put("fortaleza-tsc", "https://api.cartolafc.globo.com/time/fortaleza-tsc");
        times.put("tricolor-tuta-fc", "https://api.cartolafc.globo.com/time/tricolor-tuta-f-c");
    }

    public HashMap<String, String> getTimes() {
        return times;
    }
}

src/main/java/br/com/naldson/parciaiscartola/model/Time.java
package br.com.naldson.parciaiscartola.model;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

public class Time implements Comparable<Time> {

    private final String nome;
    private final String escudoSvg;
    private final String nomeJogador;
    private double pontos;
    private List<Jogadores> jogadores = new ArrayList<Jogadores>(11);
    private String slug;

    public Time(String nome, String escudoSvg, String nomeJogador, String slug) {
        this.nome = nome;
        this.escudoSvg = escudoSvg;
        this.nomeJogador = nomeJogador;
        this.slug = slug;
    }

    public String getNome() {
        return nome;
    }

    public String getEscudoSvg() {
        return escudoSvg;
    }

    public String getNomeJogador() {
        return nomeJogador;
    }

    public String getFormatPontos() {
        DecimalFormat formatter = new DecimalFormat("#0.00");
        return formatter.format(this.pontos);
    }

    public double getPontos() {
        return pontos;
    }

    public void setPontos(double pontos) {
        this.pontos = pontos;
    }

    public List<Jogadores> getJogadores() {
        return jogadores;
    }

    public void setJogadores(List<Jogadores> jogadores) {
        this.jogadores = jogadores;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public int compareTo(Time outro) {
        if (outro.getPontos() > getPontos()) {
            return 1;
        }
        return -1;
    }
}

src/main/java/br/com/naldson/parciaiscartola/controller/IndexController.java
package br.com.naldson.parciaiscartola.controller;

import java.io.IOException;

import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Path;
import br.com.caelum.vraptor.Result;
import br.com.naldson.parciaiscartola.model.Time;
import br.com.naldson.parciaiscartola.util.GeraTimes;
import java.util.List;
import javax.inject.Inject;

@Controller
public class IndexController {

    private GeraTimes geraTimes;
    private Result result;
    private List<Time> times;

    @Inject
    public IndexController(GeraTimes geraTimes, Result result) {
        this.geraTimes = geraTimes;
        this.result = result;
    }

    @Deprecated
    public IndexController() {
    }

    @Path(value = "/", priority = 1)
    @Get
    public void index() throws IOException {
        times = geraTimes.geraTimes();
        if (times != null) {
            result.include("times", times);
        } else {
            result.redirectTo(this).index2();
        }
    }

    @Path("mercado-indisponivel")
    public void index2() {
    }
}

src/main/java/br/com/naldson/parciaiscartola/controller/TimeController.java
package br.com.naldson.parciaiscartola.controller;

import br.com.caelum.vraptor.Controller;
import br.com.caelum.vraptor.Get;
import br.com.caelum.vraptor.Result;
import br.com.naldson.parciaiscartola.model.Jogadores;
import br.com.naldson.parciaiscartola.model.Liga;
import br.com.naldson.parciaiscartola.model.Time;
import br.com.naldson.parciaiscartola.util.CalculaParciais;
import br.com.naldson.parciaiscartola.util.GeraTimes;
import br.com.naldson.parciaiscartola.util.PegaJsonTimes;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.inject.Inject;
import org.json.JSONException;
import org.json.JSONObject;

@Controller
public class TimeController {
    
    private Result result;
    private PegaJsonTimes jsonTimes;
    private CalculaParciais parciais;
    
    @Inject
    public TimeController(Result result, PegaJsonTimes jsonTimes, CalculaParciais parciais) {
        this.result = result;
        this.jsonTimes = jsonTimes;
        this.parciais = parciais;
    }
    
    public TimeController() {
    }
    
    @Get("time/{slug}")
    public void time(String slug) throws JSONException, IOException {
        String url = new Liga().getTimes().get(slug);
        jsonTimes.addUrl(url);
        jsonTimes.geraJson();
        List<JSONObject> j = jsonTimes.getJsons();
        
        ArrayList<Jogadores> jogadores = GeraTimes.adicionaJogadores(j.get(0));
        Time time = GeraTimes.converteJsonParaTimes(j.get(0), jogadores);
        
        Collections.sort(time.getJogadores());
        parciais.pegaParciais();
        parciais.calculaParciais(time);
        time.setPontos(parciais.getParcial());
        
        result.include("jogadores", time.getJogadores());
        result.include("time", time);
    }
    
}

src/main/webapp/WEB-INF/jsp/_comum/footer.jsp
<h4 class="h5 text-muted">
    Desenvolvido por: <a href="mailto:naldson.bc@gmail.com"><u>Naldson Chagas</u></a>
</h4>
</div>
</body>

src/main/webapp/WEB-INF/jsp/index/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<c:import url="../_comum/header.jsp"></c:import>
    <section>
        <h3 class="h3 text-center">Confira as parciais de todos os times
            da liga</h3>
        <br />

        <table class="table center table-responsive">
            <thead>
                <tr>
                    <th>Escudo</th>
                    <th>Time</th>
                    <th>Jogador</th>
                    <th>Parcial</th>
                </tr>
            </thead>

            <tbody>
            <c:forEach var="t" items="${times}">
                <tr>
                    <td><a href="time/${t.slug}"><img src="${t.escudoSvg}" width="50px" /></a></td>
                    <td><a href="time/${t.slug}"><strong>${t.nome}</strong></a></td>
                    <td><strong>${t.nomeJogador}</strong></td>
                    <td><strong style="color: green">${t.formatPontos}</strong></td>
                </tr>
            </c:forEach>
        </tbody>
    </table>
</section>
<c:import url="../_comum/footer.jsp"></c:import>

src/main/webapp/WEB-INF/jsp/time/time.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<c:import url="../_comum/header.jsp"></c:import>
    <br>
    <section class="center text-center">
        <img src="${time.escudoSvg}" width="90px"/>
    <h2>${time.nome}</h2>
    <h2 style="color: green">${time.formatPontos}</h2>
</section>
<section>
    <table class="table center table-responsive center">
        <thead>
            <tr>
                <th></th>
                <th>Foto</th>
                <th>Nome</th>
                <th>Parcial</th>
            </tr>
        </thead>
        <tbody>
        <c:forEach items="${jogadores}" var="j">
            <tr>
                <td></td>
                <td><img src="${j.foto}" id="img_jogador" width="70px"/></td>
                <td>${j.nome}</td>
                <td><strong>${j.pontos}</strong></td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
</section>
<c:import url="../_comum/footer.jsp"></c:import>